/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PickSeatsShowingIdRouteImport } from './routes/pick-seats/$showingId'
import { Route as MovieMovieIdRouteImport } from './routes/movie/$movieId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickSeatsShowingIdRoute = PickSeatsShowingIdRouteImport.update({
  id: '/pick-seats/$showingId',
  path: '/pick-seats/$showingId',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdRoute = MovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/pick-seats/$showingId': typeof PickSeatsShowingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/pick-seats/$showingId': typeof PickSeatsShowingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
  '/pick-seats/$showingId': typeof PickSeatsShowingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movie/$movieId' | '/pick-seats/$showingId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movie/$movieId' | '/pick-seats/$showingId'
  id: '__root__' | '/' | '/movie/$movieId' | '/pick-seats/$showingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovieMovieIdRoute: typeof MovieMovieIdRoute
  PickSeatsShowingIdRoute: typeof PickSeatsShowingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick-seats/$showingId': {
      id: '/pick-seats/$showingId'
      path: '/pick-seats/$showingId'
      fullPath: '/pick-seats/$showingId'
      preLoaderRoute: typeof PickSeatsShowingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovieMovieIdRoute: MovieMovieIdRoute,
  PickSeatsShowingIdRoute: PickSeatsShowingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
